#!/bin/bash

# options for borders
# colors are in ...
orange_brown=0xffC46210
light_blue=0xffC9FFE5
blood=0xFF8A0303
black=0xff181819
white=0xffe2e2e3
red=0xfffc5d7c
blood=0xFF8A0303
green=0xff9ed072
ligh_green=0xff9ef4a9
blue=0xff76cce0
cog_blue=0xff6a97b8
yellow=0xffe7c664
orange=0xfff39660
orange_brown=0xffC46210
magenta=0xffb39df3
grey=0xff7f8490
pink=0xffffc0cb
purple=0xff8a00c2
transparent=0x00000000


options=(
    # square; other option
    style=round
    width=5.0
    hidpi=off
    active_color=$ligh_green
    inactive_color=$grey
)
borders "${options[@]}"
