[general]
live_config_reload = true
working_directory = "None"
[window]
decorations = "None"
opacity = 0.7
[font]
size = 16
[font.normal]
family = "MesloLGS NF"
[cursor]
style.shape = "Block"
style.blinking = "Always"
[colors.cursor]
text = "#131c14"
cursor = "#9ef4a9"
