local apps <const> = {
	["Live"] = "\u{f26c}", -- Assuming Ableton Live, using a music-related icon (Font Awesome)
	["Adobe Bridge 2024"] = "\u{e65f}", -- Adobe generic or bridge-like icon (Devicons)
	["Affinity Designer"] = "\u{e65e}", -- Design-related icon (approximation)
	["Affinity Designer 2"] = "\u{e65e}", -- Same as above
	["Affinity Photo"] = "\u{f03e}", -- Photo icon (Font Awesome)
	["Affinity Photo 2"] = "\u{f03e}", -- Same as above
	["Affinity Publisher"] = "\u{f1ea}", -- Newspaper/book icon (Font Awesome)
	["Affinity Publisher 2"] = "\u{f1ea}", -- Same as above
	["Airmail"] = "\u{f0e0}", -- Envelope icon (Font Awesome)
	["Alacritty"] = "\u{f120}", -- Terminal icon (Font Awesome)
	["Alfred Preferences"] = "\u{f013}", -- Gear icon for settings (Font Awesome)
	["Android Messages"] = "\u{e624}", -- Android SMS icon (Devicons)
	["Android Studio"] = "\u{e70c}", -- Android Studio icon (Devicons)
	["Anytype"] = "\u{f15c}", -- Generic document icon (Font Awesome)
	["App Eraser"] = "\u{f2ed}", -- Trash icon (Font Awesome)
	["App Store"] = "\u{f3ab}", -- Store-like icon (Font Awesome)
	["Arc"] = "\u{f7a0}", -- Browser-like arc icon (approximation)
	["Atom"] = "\u{e764}", -- Atom icon (Devicons)
	["Audacity"] = "\u{f025}", -- Audio icon (Font Awesome)
	["Bambu Studio"] = "\u{f5ab}", -- 3D print-related icon (approximation)
	["MoneyMoney"] = "\u{f53a}", -- Bank icon (Font Awesome)
	["Bear"] = "\u{f1fc}", -- Writing/pencil icon (Font Awesome)
	["BetterTouchTool"] = "\u{f25a}", -- Tool icon (Font Awesome)
	["Bilibili"] = "\u{f167}", -- Video platform (YouTube-like, Font Awesome)
	["哔哩哔哩"] = "\u{f167}", -- Same as Bilibili
	["Bitwarden"] = "\u{f023}", -- Lock icon (Font Awesome)
	["Blender"] = "\u{e728}", -- Blender icon (Devicons)
	["BluOS Controller"] = "\u{f001}", -- Music icon (Font Awesome)
	["Calibre"] = "\u{f02d}", -- Book icon (Font Awesome)
	["Brave Browser"] = "\u{e77d}", -- Brave icon (Devicons)
	["Calculator"] = "\u{f1ec}", -- Calculator icon (Font Awesome)
	["Soulver 3"] = "\u{f1ec}", -- Same as above
	["Calculette"] = "\u{f1ec}", -- Same as above
	["Calendar"] = "\u{f073}", -- Calendar icon (Font Awesome)
	["日历"] = "\u{f073}", -- Same as above
	["Fantastical"] = "\u{f073}", -- Same as above
	["Cron"] = "\u{f073}", -- Same as above
	["Amie"] = "\u{f073}", -- Same as above
	["Calendrier"] = "\u{f073}", -- Same as above
	["Notion Calendar"] = "\u{f073}", -- Same as above
	["Caprine"] = "\u{f086}", -- Chat icon (Font Awesome)
	["Citrix Workspace"] = "\u{f0c2}", -- Cloud icon (Font Awesome)
	["Citrix Viewer"] = "\u{f0c2}", -- Same as above
	["ClickUp"] = "\u{f0ae}", -- Task list icon (Font Awesome)
	["Code"] = "\u{e71e}", -- VS Code icon (Devicons)
	["Code - Insiders"] = "\u{e71e}", -- Same as above
	["Color Picker"] = "\u{f1fb}", -- Eye dropper icon (Font Awesome)
	["数码测色计"] = "\u{f1fb}", -- Same as above
	["CotEditor"] = "\u{f044}", -- Edit icon (Font Awesome)
	["Cypress"] = "\u{e725}", -- Cypress icon (Devicons)
	["DataGrip"] = "\u{e7b4}", -- JetBrains DB icon (Devicons)
	["DataSpell"] = "\u{e7b2}", -- JetBrains Data icon (Devicons)
	["DaVinci Resolve"] = "\u{f03d}", -- Video icon (Font Awesome)
	["Default"] = "\u{f111}", -- Circle/default icon (Font Awesome)
	["CleanMyMac X"] = "\u{f2f9}", -- Broom/cleaning icon (Font Awesome)
	["DEVONthink 3"] = "\u{f15c}", -- Document icon (Font Awesome)
	["DingTalk"] = "\u{f075}", -- Comment/chat icon (Font Awesome)
	["钉钉"] = "\u{f075}", -- Same as above
	["阿里钉"] = "\u{f075}", -- Same as above
	["Discord"] = "\u{f392}", -- Discord icon (Font Awesome)
	["Discord Canary"] = "\u{f392}", -- Same as above
	["Discord PTB"] = "\u{f392}", -- Same as above
	["Docker"] = "\u{f395}", -- Docker icon (Font Awesome)
	["Docker Desktop"] = "\u{f395}", -- Same as above
	["GrandTotal"] = "\u{f155}", -- Dollar sign (Font Awesome)
	["Receipts"] = "\u{f155}", -- Same as above
	["Double Commander"] = "\u{f07b}", -- Folder icon (Font Awesome)
	["Drafts"] = "\u{f15b}", -- Draft icon (Font Awesome)
	["Dropbox"] = "\u{f16b}", -- Dropbox icon (Font Awesome)
	["Element"] = "\u{f086}", -- Chat icon (Font Awesome)
	["Emacs"] = "\u{e632}", -- Emacs icon (Devicons)
	["Evernote Legacy"] = "\u{f24d}", -- Evernote icon (Font Awesome)
	["FaceTime"] = "\u{f095}", -- Phone icon (Font Awesome)
	["FaceTime 通话"] = "\u{f095}", -- Same as above
	["Figma"] = "\u{f699}", -- Figma icon (Font Awesome)
	["Final Cut Pro"] = "\u{f03d}", -- Video icon (Font Awesome)
	["Finder"] = "\u{f07c}", -- Folder open icon (Font Awesome)
	["访达"] = "\u{f07c}", -- Same as above
	["Firefox"] = "\u{e75c}", -- Firefox icon (Devicons)
	["Firefox Developer Edition"] = "\u{e75c}", -- Same as above
	["Firefox Nightly"] = "\u{e75c}", -- Same as above
	["Folx"] = "\u{f019}", -- Download icon (Font Awesome)
	["Fusion"] = "\u{f126}", -- Code branch icon (Font Awesome)
	["System Preferences"] = "\u{f013}", -- Gear icon (Font Awesome)
	["System Settings"] = "\u{f013}", -- Same as above
	["Systemeinstellungen"] = "\u{f013}", -- Same as above
	["系统设置"] = "\u{f013}", -- Same as above
	["Réglages Système"] = "\u{f013}", -- Same as above
	["GitHub Desktop"] = "\u{f09b}", -- GitHub icon (Font Awesome)
	["Godot"] = "\u{e73b}", -- Godot icon (Devicons)
	["GoLand"] = "\u{e724}", -- GoLand icon (Devicons)
	["Chromium"] = "\u{e743}", -- Chromium icon (Devicons)
	["Google Chrome"] = "\u{e743}", -- Chrome icon (Devicons)
	["Google Chrome Canary"] = "\u{e743}", -- Same as above
	["Grammarly Editor"] = "\u{f044}", -- Edit icon (Font Awesome)
	["Home Assistant"] = "\u{f015}", -- Home icon (Font Awesome)
	["Hyper"] = "\u{f120}", -- Terminal icon (Font Awesome)
	["IntelliJ IDEA"] = "\u{e7b5}", -- IntelliJ icon (Devicons)
	["Inkdrop"] = "\u{f15c}", -- Note icon (Font Awesome)
	["Inkscape"] = "\u{e634}", -- Inkscape icon (Devicons)
	["Insomnia"] = "\u{f186}", -- Moon/sleep icon (Font Awesome)
	["Iris"] = "\u{f06e}", -- Eye icon (Font Awesome)
	["iTerm"] = "\u{f120}", -- Terminal icon (Font Awesome)
	["iTerm2"] = "\u{f120}", -- Same as above
	["Jellyfin Media Player"] = "\u{f144}", -- Play circle icon (Font Awesome)
	["Joplin"] = "\u{f15c}", -- Note icon (Font Awesome)
	["카카오톡"] = "\u{f075}", -- Chat icon (Font Awesome)
	["KakaoTalk"] = "\u{f075}", -- Same as above
	["Kakoune"] = "\u{f044}", -- Edit icon (Font Awesome)
	["KeePassXC"] = "\u{f084}", -- Key icon (Font Awesome)
	["Secrets"] = "\u{f023}", -- Lock icon (Font Awesome)
	["Keyboard Maestro"] = "\u{f11c}", -- Keyboard icon (Font Awesome)
	["Keynote"] = "\u{f1ea}", -- Presentation icon (Font Awesome)
	["Keynote 讲演"] = "\u{f1ea}", -- Same as above
	["kitty"] = "\u{f120}", -- Terminal icon (Font Awesome)
	["League of Legends"] = "\u{f11b}", -- Gamepad icon (Font Awesome)
	["LibreWolf"] = "\u{e75c}", -- Firefox-like icon (Devicons)
	["Adobe Lightroom"] = "\u{e65b}", -- Lightroom icon (Devicons)
	["Lightroom Classic"] = "\u{e65b}", -- Same as above
	["LINE"] = "\u{f3c0}", -- LINE icon (Font Awesome)
	["Linear"] = "\u{f0ae}", -- Task icon (Font Awesome)
	["LM Studio"] = "\u{f15c}", -- Generic studio icon (Font Awesome)
	["LocalSend"] = "\u{f019}", -- Download/share icon (Font Awesome)
	["Logic Pro"] = "\u{f001}", -- Music icon (Font Awesome)
	["Logseq"] = "\u{f15c}", -- Note icon (Font Awesome)
	["Canary Mail"] = "\u{f0e0}", -- Email icon (Font Awesome)
	["HEY"] = "\u{f0e0}", -- Same as above
	["Mail"] = "\u{f0e0}", -- Same as above
	["Mailspring"] = "\u{f0e0}", -- Same as above
	["MailMate"] = "\u{f0e0}", -- Same as above
	["Superhuman"] = "\u{f0e0}", -- Same as above
	["邮件"] = "\u{f0e0}", -- Same as above
	["MAMP"] = "\u{f233}", -- Server icon (Font Awesome)
	["MAMP PRO"] = "\u{f233}", -- Same as above
	["Maps"] = "\u{f3c5}", -- Map icon (Font Awesome)
	["Google Maps"] = "\u{f3c5}", -- Same as above
	["Matlab"] = "\u{f0ae}", -- Math/task icon (Font Awesome)
	["Mattermost"] = "\u{f086}", -- Chat icon (Font Awesome)
	["Messages"] = "\u{f0e5}", -- Comment dots icon (Font Awesome)
	["信息"] = "\u{f0e5}", -- Same as above
	["Nachrichten"] = "\u{f0e5}", -- Same as above
	["Messenger"] = "\u{f39f}", -- Messenger icon (Font Awesome)
	["Microsoft Edge"] = "\u{e77f}", -- Edge icon (Devicons)
	["Microsoft Excel"] = "\u{e67c}", -- Excel icon (Devicons)
	["Microsoft Outlook"] = "\u{e67e}", -- Outlook icon (Devicons)
	["Microsoft PowerPoint"] = "\u{e67f}", -- PowerPoint icon (Devicons)
	["Microsoft Remote Desktop"] = "\u{f108}", -- Desktop icon (Font Awesome)
	["Microsoft Teams"] = "\u{f4b7}", -- Teams icon (Font Awesome)
	["Microsoft Teams (work or school)"] = "\u{f4b7}", -- Same as above
	["Microsoft Word"] = "\u{e680}", -- Word icon (Devicons)
	["Min"] = "\u{f26a}", -- Browser-like icon (Font Awesome)
	["Miro"] = "\u{f12f}", -- Board icon (Font Awesome)
	["MongoDB Compass"] = "\u{e63e}", -- MongoDB icon (Devicons)
	["mpv"] = "\u{f144}", -- Play circle icon (Font Awesome)
	["Mullvad Browser"] = "\u{f503}", -- Shield/anon icon (Font Awesome)
	["Music"] = "\u{f001}", -- Music icon (Font Awesome)
	["音乐"] = "\u{f001}", -- Same as above
	["Musique"] = "\u{f001}", -- Same as above
	["Neovide"] = "\u{e7c5}", -- Vim-like icon (Devicons)
	["neovide"] = "\u{e7c5}", -- Same as above
	["Neovim"] = "\u{e7c5}", -- Neovim icon (Devicons)
	["neovim"] = "\u{e7c5}", -- Same as above
	["nvim"] = "\u{e7c5}", -- Same as above
	["网易云音乐"] = "\u{f001}", -- Music icon (Font Awesome)
	["Noodl"] = "\u{f0c5}", -- Nodes/connection icon (Font Awesome)
	["Noodl Editor"] = "\u{f0c5}", -- Same as above
	["NordVPN"] = "\u{f023}", -- Lock/VPN icon (Font Awesome)
	["Notability"] = "\u{f15c}", -- Note icon (Font Awesome)
	["Notes"] = "\u{f15c}", -- Note icon (Font Awesome)
	["Notizen"] = "\u{f15c}", -- Same as above
	["备忘录"] = "\u{f15c}", -- Same as above
	["Notion"] = "\u{e727}", -- Notion icon (Devicons)
	["Nova"] = "\u{f005}", -- Star/new icon (Font Awesome)
	["Numbers"] = "\u{f1ec}", -- Table/calc icon (Font Awesome)
	["Numbers 表格"] = "\u{f1ec}", -- Same as above
	["Obsidian"] = "\u{e73e}", -- Obsidian icon (Devicons)
	["OBS"] = "\u{f03d}", -- Video/stream icon (Font Awesome)
	["OmniFocus"] = "\u{f0ae}", -- Task icon (Font Awesome)
	["1Password"] = "\u{f023}", -- Lock icon (Font Awesome)
	["ChatGPT"] = "\u{f0c9}", -- AI/chat icon (Font Awesome)
	["OpenVPN Connect"] = "\u{f023}", -- Lock/VPN icon (Font Awesome)
	["Opera"] = "\u{e77e}", -- Opera icon (Devicons)
	["OrcaSlicer"] = "\u{f5ab}", -- 3D print icon (Font Awesome)
	["Orion"] = "\u{f135}", -- Rocket/browser icon (Font Awesome)
	["Orion RC"] = "\u{f135}", -- Same as above
	["Pages"] = "\u{f15b}", -- Document icon (Font Awesome)
	["Pages 文稿"] = "\u{f15b}", -- Same as above
	["Parallels Desktop"] = "\u{f108}", -- Desktop icon (Font Awesome)
	["Parsec"] = "\u{f11b}", -- Gamepad/remote icon (Font Awesome)
	["Preview"] = "\u{f1c1}", -- PDF icon (Font Awesome)
	["预览"] = "\u{f1c1}", -- Same as above
	["Skim"] = "\u{f1c1}", -- Same as above
	["zathura"] = "\u{f1c1}", -- Same as above
	["Aperçu"] = "\u{f1c1}", -- Same as above
	["PDF Expert"] = "\u{f1c1}", -- Same as above
	["Adobe Photoshop"] = "\u{e65d}", -- Photoshop icon (Devicons)
	["Pi-hole Remote"] = "\u{f0c2}", -- Cloud/network icon (Font Awesome)
	["Pine"] = "\u{f075}", -- Chat/email icon (Font Awesome)
	["Podcasts"] = "\u{f2ce}", -- Podcast icon (Font Awesome)
	["播客"] = "\u{f2ce}", -- Same as above
	["PomoDone App"] = "\u{f017}", -- Clock icon (Font Awesome)
	["Postman"] = "\u{f0ec}", -- API/send icon (Font Awesome)
	["PrusaSlicer"] = "\u{f5ab}", -- 3D print icon (Font Awesome)
	["SuperSlicer"] = "\u{f5ab}", -- Same as above
	["PyCharm"] = "\u{e706}", -- PyCharm icon (Devicons)
	["QQ"] = "\u{f075}", -- Chat icon (Font Awesome)
	["QQ音乐"] = "\u{f001}", -- Music icon (Font Awesome)
	["QQMusic"] = "\u{f001}", -- Same as above
	["Quantumult X"] = "\u{f0c2}", -- Network/proxy icon (Font Awesome)
	["qutebrowser"] = "\u{f26a}", -- Browser icon (Font Awesome)
	["Raindrop.io"] = "\u{f5c6}", -- Bookmark icon (Font Awesome)
	["Reeder"] = "\u{f09e}", -- RSS icon (Font Awesome)
	["Reminders"] = "\u{f0f3}", -- Bell/reminder icon (Font Awesome)
	["提醒事项"] = "\u{f0f3}", -- Same as above
	["Rappels"] = "\u{f0f3}", -- Same as above
	["Replit"] = "\u{f121}", -- Code icon (Font Awesome)
	["Rider"] = "\u{e7b7}", -- Rider icon (Devicons)
	["JetBrains Rider"] = "\u{e7b7}", -- Same as above
	["Safari"] = "\u{e74f}", -- Safari icon (Devicons)
	["Safari浏览器"] = "\u{e74f}", -- Same as above
	["Safari Technology Preview"] = "\u{e74f}", -- Same as above
	["Sequel Ace"] = "\u{f1c0}", -- Database icon (Font Awesome)
	["Sequel Pro"] = "\u{f1c0}", -- Same as above
	["Setapp"] = "\u{f019}", -- Download/app icon (Font Awesome)
	["SF Symbols"] = "\u{f12e}", -- Symbol/icon icon (Font Awesome)
	["Signal"] = "\u{f086}", -- Chat icon (Font Awesome)
	["Sketch"] = "\u{e735}", -- Sketch icon (Devicons)
	["Skype"] = "\u{f17e}", -- Skype icon (Font Awesome)
	["Slack"] = "\u{f198}", -- Slack icon (Font Awesome)
	["Spark"] = "\u{f0e0}", -- Email icon (Font Awesome)
	["Spotify"] = "\u{f1bc}", -- Spotify icon (Font Awesome)
	["Spotlight"] = "\u{f002}", -- Search icon (Font Awesome)
	["Sublime Text"] = "\u{e7aa}", -- Sublime Text icon (Devicons)
	["Tana"] = "\u{f15c}", -- Note icon (Font Awesome)
	["TeamSpeak 3"] = "\u{f4b6}", -- Teamspeak icon (Font Awesome)
	["Telegram"] = "\u{f2c6}", -- Telegram icon (Font Awesome)
	["Terminal"] = "\u{f120}", -- Terminal icon (Font Awesome)
	["终端"] = "\u{f120}", -- Same as above
	["Typora"] = "\u{f15c}", -- Text icon (Font Awesome)
	["Microsoft To Do"] = "\u{f0ae}", -- Task icon (Font Awesome)
	["Things"] = "\u{f0ae}", -- Same as above
	["Thunderbird"] = "\u{e716}", -- Thunderbird icon (Devicons)
	["TickTick"] = "\u{f017}", -- Clock/task icon (Font Awesome)
	["TIDAL"] = "\u{f001}", -- Music icon (Font Awesome)
	["Tiny RDM"] = "\u{f1c0}", -- Database icon (Font Awesome)
	["Todoist"] = "\u{f0ae}", -- Task icon (Font Awesome)
	["Toggl Track"] = "\u{f017}", -- Clock icon (Font Awesome)
	["Tor Browser"] = "\u{f503}", -- Anon/shield icon (Font Awesome)
	["Tower"] = "\u{f126}", -- Git branch icon (Font Awesome)
	["Transmit"] = "\u{f019}", -- Download/upload icon (Font Awesome)
	["Trello"] = "\u{f181}", -- Trello icon (Font Awesome)
	["Tweetbot"] = "\u{f099}", -- Twitter icon (Font Awesome)
	["Twitter"] = "\u{f099}", -- Same as above
	["MacVim"] = "\u{e7c5}", -- Vim icon (Devicons)
	["Vim"] = "\u{e7c5}", -- Same as above
	["VimR"] = "\u{e7c5}", -- Same as above
	["Vivaldi"] = "\u{e77b}", -- Vivaldi icon (Devicons)
	["VLC"] = "\u{f144}", -- Play circle icon (Font Awesome)
	["VMware Fusion"] = "\u{f108}", -- Desktop/VM icon (Font Awesome)
	["VSCodium"] = "\u{e71e}", -- VS Code-like icon (Devicons)
	["Warp"] = "\u{f120}", -- Terminal icon (Font Awesome)
	["WebStorm"] = "\u{e7b0}", -- WebStorm icon (Devicons)
	["微信"] = "\u{f1d7}", -- WeChat icon (Font Awesome)
	["WeChat"] = "\u{f1d7}", -- Same as above
	["企业微信"] = "\u{f1d7}", -- Same as above (WeCom)
	["WeCom"] = "\u{f1d7}", -- Same as above
	["WezTerm"] = "\u{f120}", -- Terminal icon (Font Awesome)
	["WhatsApp"] = "\u{f232}", -- WhatsApp icon (Font Awesome)
	["WhatsApp"] = "\u{f232}", -- Same as above
	["Xcode"] = "\u{e711}", -- Xcode icon (Devicons)
	["Яндекс Музыка"] = "\u{f001}", -- Music icon (Font Awesome)
	["Yuque"] = "\u{f15c}", -- Note icon (Font Awesome)
	["语雀"] = "\u{f15c}", -- Same as above
	["Zed"] = "\u{f044}", -- Edit icon (Font Awesome)
	["Zeplin"] = "\u{f280}", -- Design/board icon (Font Awesome)
	["zoom.us"] = "\u{f03d}", -- Video icon (Font Awesome)
	["Zotero"] = "\u{f02d}", -- Book/reference icon (Font Awesome)
	["Zulip"] = "\u{f086}", -- Chat icon (Font Awesome)
	["default"] = "\u{f111}", -- Circle/default icon (Font Awesome)
}

local text <const> = {
	nerdfont = {
		plus = "􀅼",
		loading = "􀖇",
		apple = "􀣺",
		gear = "􀍟",
		cpu = "􀫥",
		clipboard = "􀉄",

		switch = {
			on = "􁏮",
			off = "􁏯",
		},
		volume = {
			_100 = "􀊩",
			_66 = "􀊧",
			_33 = "􀊥",
			_10 = "􀊡",
			_0 = "􀊣",
		},
		battery = {
			_100 = "􀛨",
			_75 = "􀺸",
			_50 = "􀺶",
			_25 = "􀛩",
			_0 = "􀛪",
			charging = "􀢋",
		},
		wifi = {
			upload = "􀄨",
			download = "􀄩",
			connected = "􀙇",
			disconnected = "􀙈",
			router = "􁓤",
		},
		media = {
			back = "􀊊",
			forward = "􀊌",
			play_pause = "􀊈",
		},
		slider = {
			knob = "",
		},
	},
	sf_symbols = {
		plus = "􀅼",
		loading = "􀖇",
		apple = "􀣺",
		gear = "􀍟",
		cpu = "􀫥",
		clipboard = "􀉄",

		switch = {
			on = "􁏮",
			off = "􁏯",
		},
		volume = {
			_100 = "􀊩",
			_66 = "􀊧",
			_33 = "􀊥",
			_10 = "􀊡",
			_0 = "􀊣",
		},
		battery = {
			_100 = "􀛨",
			_75 = "􀺸",
			_50 = "􀺶",
			_25 = "􀛩",
			_0 = "􀛪",
			charging = "􀢋",
		},
		wifi = {
			upload = "􀄨",
			download = "􀄩",
			connected = "􀙇",
			disconnected = "􀙈",
			router = "􁓤",
		},
		media = {
			back = "􀊊",
			forward = "􀊌",
			play_pause = "􀊈",
		},
	},
}
return {
	text = text,
	apps = apps,
}
